{cluster: '75', cutoff: '30', density: '700', intervals: ./ppmc_interval_index.csv,
  local: '50', output_directory: 'C:/Users/user/Documents/Unief/Vakantiejob/microbiology-spectrum-analysis/GUI',
  project_directory: 'C:/Users/user/Documents/Unief/Vakantiejob/microbiology-spectrum-analysis/Data/data_BURK_EXP1/burk_merged'}
